"""内置旅行知识语料：景点、美食、交通枢纽与攻略片段。

语料带来源字段，用于 RAG 检索与防幻觉约束；后续可替换为 pgvector 生产库。
"""

CITIES = ["北京", "成都", "上海", "天津"]

ATTRACTIONS = [
    {
        "name": "故宫博物院",
        "city": "北京",
        "lat": 39.9163,
        "lon": 116.3972,
        "duration_hours": 3.5,
        "opening_hours": "08:30-17:00",
        "fee": 60,
        "tags": ["历史", "文化", "地标", "预约"],
        "source": "北京旅游官方攻略",
        "category": "attraction",
        "note": "周一闭馆，需提前预约",
    },
    {
        "name": "天安门广场",
        "city": "北京",
        "lat": 39.9055,
        "lon": 116.3976,
        "duration_hours": 1.5,
        "opening_hours": "05:00-22:00",
        "fee": 0,
        "tags": ["地标", "历史", "拍照"],
        "source": "北京旅游官方攻略",
        "category": "attraction",
        "note": "升旗时间随季节变化",
    },
    {
        "name": "颐和园",
        "city": "北京",
        "lat": 39.9999,
        "lon": 116.2755,
        "duration_hours": 4,
        "opening_hours": "06:30-18:00",
        "fee": 30,
        "tags": ["园林", "自然", "拍照"],
        "source": "北京旅游官方攻略",
        "category": "attraction",
        "note": "东宫门与北宫门可入园",
    },
    {
        "name": "南锣鼓巷",
        "city": "北京",
        "lat": 39.9364,
        "lon": 116.4039,
        "duration_hours": 2,
        "opening_hours": "全天",
        "fee": 0,
        "tags": ["街区", "美食", "拍照"],
        "source": "胡同美食攻略",
        "category": "attraction",
        "note": "周末人流较大",
    },
    {
        "name": "八达岭长城",
        "city": "北京",
        "lat": 40.3541,
        "lon": 116.0195,
        "duration_hours": 5,
        "opening_hours": "06:30-19:00",
        "fee": 40,
        "tags": ["自然", "历史", "地标"],
        "source": "北京旅游官方攻略",
        "category": "attraction",
        "note": "离市区约 70 公里，需预留交通时间",
    },
    {
        "name": "宽窄巷子",
        "city": "成都",
        "lat": 30.6688,
        "lon": 104.0554,
        "duration_hours": 2.5,
        "opening_hours": "全天",
        "fee": 0,
        "tags": ["街区", "美食", "文化", "拍照"],
        "source": "成都文旅攻略",
        "category": "attraction",
        "note": "适合傍晚逛，小吃集中",
    },
    {
        "name": "成都大熊猫繁育研究基地",
        "city": "成都",
        "lat": 30.7353,
        "lon": 104.1435,
        "duration_hours": 3.5,
        "opening_hours": "07:30-18:00",
        "fee": 55,
        "tags": ["亲子", "自然", "拍照", "预约"],
        "source": "成都文旅攻略",
        "category": "attraction",
        "note": "上午熊猫更活跃，建议 8 点前入园",
    },
    {
        "name": "武侯祠",
        "city": "成都",
        "lat": 30.6465,
        "lon": 104.0477,
        "duration_hours": 2,
        "opening_hours": "09:00-18:00",
        "fee": 50,
        "tags": ["历史", "文化"],
        "source": "成都文旅攻略",
        "category": "attraction",
        "note": "与锦里相邻，可安排同一时段",
    },
    {
        "name": "锦里古街",
        "city": "成都",
        "lat": 30.6463,
        "lon": 104.0482,
        "duration_hours": 2,
        "opening_hours": "全天",
        "fee": 0,
        "tags": ["街区", "美食", "拍照"],
        "source": "成都文旅攻略",
        "category": "attraction",
        "note": "夜景漂亮，适合晚饭后散步",
    },
    {
        "name": "都江堰景区",
        "city": "成都",
        "lat": 31.0014,
        "lon": 103.6203,
        "duration_hours": 4,
        "opening_hours": "08:00-18:00",
        "fee": 80,
        "tags": ["自然", "历史", "水利"],
        "source": "成都文旅攻略",
        "category": "attraction",
        "note": "距市区约 60 公里，建议包车或高铁",
    },
    {
        "name": "外滩",
        "city": "上海",
        "lat": 31.2400,
        "lon": 121.4900,
        "duration_hours": 2,
        "opening_hours": "全天",
        "fee": 0,
        "tags": ["地标", "拍照", "夜景"],
        "source": "上海城市漫游指南",
        "category": "attraction",
        "note": "夜晚灯光效果最佳",
    },
    {
        "name": "豫园",
        "city": "上海",
        "lat": 31.2260,
        "lon": 121.4920,
        "duration_hours": 2,
        "opening_hours": "09:00-16:30",
        "fee": 40,
        "tags": ["园林", "文化", "历史"],
        "source": "上海城市漫游指南",
        "category": "attraction",
        "note": "与城隍庙小吃街相邻",
    },
    {
        "name": "上海迪士尼乐园",
        "city": "上海",
        "lat": 31.1434,
        "lon": 121.6570,
        "duration_hours": 10,
        "opening_hours": "08:30-21:30",
        "fee": 475,
        "tags": ["亲子", "乐园", "拍照", "预约"],
        "source": "上海城市漫游指南",
        "category": "attraction",
        "note": "需单独留一整天，建议买早享卡",
    },
    {
        "name": "武康路",
        "city": "上海",
        "lat": 31.2095,
        "lon": 121.4348,
        "duration_hours": 2,
        "opening_hours": "全天",
        "fee": 0,
        "tags": ["街区", "拍照", "咖啡"],
        "source": "上海城市漫游指南",
        "category": "attraction",
        "note": "适合步行与街拍",
    },
    {
        "name": "田子坊",
        "city": "上海",
        "lat": 31.2120,
        "lon": 121.4650,
        "duration_hours": 2,
        "opening_hours": "10:00-21:00",
        "fee": 0,
        "tags": ["街区", "艺术", "美食"],
        "source": "上海城市漫游指南",
        "category": "attraction",
        "note": "弄堂较窄，注意保管随身物品",
    },
]

FOODS = [
    {
        "name": "北京烤鸭",
        "city": "北京",
        "tags": ["美食", "必吃"],
        "source": "胡同美食攻略",
        "price": 120,
        "note": "推荐全聚德/四季民福，建议提前取号",
    },
    {
        "name": "铜锅涮肉",
        "city": "北京",
        "tags": ["美食", "火锅"],
        "source": "胡同美食攻略",
        "price": 100,
        "note": "老北京铜锅，适合秋冬",
    },
    {
        "name": "炸酱面",
        "city": "北京",
        "tags": ["美食", "主食"],
        "source": "胡同美食攻略",
        "price": 30,
        "note": "方砖厂等老字号排队较多",
    },
    {
        "name": "成都火锅",
        "city": "成都",
        "tags": ["美食", "火锅", "必吃"],
        "source": "成都美食地图",
        "price": 90,
        "note": "推荐麻辣锅底，可配冰粉解辣",
    },
    {
        "name": "串串香",
        "city": "成都",
        "tags": ["美食", "小吃"],
        "source": "成都美食地图",
        "price": 60,
        "note": "按签计价，适合多人分享",
    },
    {
        "name": "担担面",
        "city": "成都",
        "tags": ["美食", "主食"],
        "source": "成都美食地图",
        "price": 15,
        "note": "甜水面、钟水饺也值得尝试",
    },
    {
        "name": "小笼包",
        "city": "上海",
        "tags": ["美食", "必吃"],
        "source": "上海早餐指南",
        "price": 35,
        "note": "建议现点现吃，先咬一小口喝汤",
    },
    {
        "name": "生煎包",
        "city": "上海",
        "tags": ["美食", "早餐"],
        "source": "上海早餐指南",
        "price": 25,
        "note": "底部焦脆，趁热吃",
    },
    {
        "name": "本帮红烧肉",
        "city": "上海",
        "tags": ["美食", "正餐"],
        "source": "上海城市漫游指南",
        "price": 80,
        "note": "浓油赤酱，适合搭配米饭",
    },
]

TRANSPORT_HUBS = [
    {
        "name": "北京大兴国际机场",
        "city": "北京",
        "lat": 39.5098,
        "lon": 116.4105,
        "tags": ["交通", "机场"],
        "source": "北京交通指南",
    },
    {
        "name": "北京南站",
        "city": "北京",
        "lat": 39.8652,
        "lon": 116.3789,
        "tags": ["交通", "高铁"],
        "source": "北京交通指南",
    },
    {
        "name": "成都天府国际机场",
        "city": "成都",
        "lat": 30.3126,
        "lon": 104.4416,
        "tags": ["交通", "机场"],
        "source": "成都交通指南",
    },
    {
        "name": "成都东站",
        "city": "成都",
        "lat": 30.6300,
        "lon": 104.1400,
        "tags": ["交通", "高铁"],
        "source": "成都交通指南",
    },
    {
        "name": "上海浦东国际机场",
        "city": "上海",
        "lat": 31.1443,
        "lon": 121.8083,
        "tags": ["交通", "机场"],
        "source": "上海交通指南",
    },
    {
        "name": "上海虹桥站",
        "city": "上海",
        "lat": 31.1933,
        "lon": 121.3196,
        "tags": ["交通", "高铁"],
        "source": "上海交通指南",
    },
]

GUIDE_SNIPPETS = [
    {
        "city": "北京",
        "title": "北京三日经典路线",
        "content": "第一天故宫、景山、南锣鼓巷；第二天长城、鸟巢；第三天颐和园、圆明园。建议避开周一闭馆日。",
        "source": "北京旅游官方攻略",
    },
    {
        "city": "成都",
        "title": "成都美食两日游",
        "content": "第一天宽窄巷子、武侯祠、锦里，晚上火锅；第二天熊猫基地、都江堰。熊猫基地建议早去。",
        "source": "成都文旅攻略",
    },
    {
        "city": "上海",
        "title": "上海 Citywalk 两日路线",
        "content": "第一天外滩、豫园、城隍庙；第二天武康路、田子坊。迪士尼单独安排一整天。",
        "source": "上海城市漫游指南",
    },
]


def build_docs() -> list[dict]:
    docs: list[dict] = []
    sections = [
        (ATTRACTIONS, "attraction"),
        (FOODS, "food"),
        (TRANSPORT_HUBS, "transport"),
        (GUIDE_SNIPPETS, "guide"),
    ]
    for items, category in sections:
        for item in items:
            name = item.get("name") or item.get("title", "")
            content = " ".join(
                [
                    name,
                    item.get("city", ""),
                    item.get("note", ""),
                    item.get("content", ""),
                    " ".join(item.get("tags", [])),
                ]
            ).strip()
            docs.append(
                {
                    "id": name,
                    "name": name,
                    "city": item.get("city", ""),
                    "content": content,
                    "source": item.get("source", "内置语料"),
                    "category": category,
                    "lat": item.get("lat"),
                    "lon": item.get("lon"),
                    "duration_hours": item.get("duration_hours", 0),
                    "opening_hours": item.get("opening_hours", "全天"),
                    "fee": item.get("fee", item.get("price", 0)),
                    "tags": item.get("tags", []),
                    "note": item.get("note", ""),
                    "title": item.get("title", name),
                }
            )
    return docs

